from __future__ import annotations

from typing import Protocol

from server.app.player.models import (
    DatabaseUpdateStatus,
    MPDStats,
    OutputInfo,
    PlayerQueueEntry,
    PlayerStatus,
)


class PlayerUnavailable(RuntimeError):
    """The playback engine cannot currently be reached."""


class PlayerCommandError(RuntimeError):
    """The playback engine rejected a command."""

    def __init__(
        self,
        command: str,
        message: str,
        *,
        error_code: int | None = None,
        command_list_index: int | None = None,
    ) -> None:
        super().__init__(message)
        self.command = command
        self.error_code = error_code
        self.command_list_index = command_list_index


class PlayerPort(Protocol):
    async def status(self) -> PlayerStatus: ...
    async def play(self, song_uri: str | None = None) -> None: ...
    async def pause(self) -> None: ...
    async def stop(self) -> None: ...
    async def next(self) -> None: ...
    async def previous(self) -> None: ...
    async def seek(self, seconds: float) -> None: ...
    async def set_repeat(self, enabled: bool) -> None: ...
    async def set_random(self, enabled: bool) -> None: ...
    async def set_volume(self, volume: int) -> None: ...
    async def update_database(self) -> None: ...
    async def outputs(self) -> list[OutputInfo]: ...
    async def queue_entries(self) -> list[PlayerQueueEntry]: ...
    async def queue_clear(self) -> None: ...
    async def queue_add(self, song_uri: str) -> int: ...
    async def queue_delete(self, mpd_song_id: int) -> None: ...
    async def queue_move(
        self,
        mpd_song_id: int,
        before_mpd_song_id: int | None,
    ) -> None: ...
    async def queue_play(self, mpd_song_id: int) -> None: ...
    async def set_output_enabled(self, output_id: int, enabled: bool) -> None: ...
    async def stats(self) -> MPDStats: ...
    async def database_update_status(self) -> DatabaseUpdateStatus: ...
